version: '2'
services:
  nido_users:  
    build: .
    command: bundle exec ruby main.rb
    ports:
      - "3000:4567"
    volumes:
      - ".:/app"
    environment:
      DATABASE_DEV: "db"
      RAILS_ENV: production
      RACK_ENV: production

